version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - cd $READTHEDOCS_OUTPUT
    - mkdir  _build
    - cd ./_build
    - mkdir html
    - cd ./html
    - mkdir _static
    - cd ./_static
    - cp docs/resources/interview_Melo.mp3 ./interview_Melo.mp3

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
