version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/_static
      - cp docs/resources/interview_Melo.mp3 $READTHEDOCS_OUTPUT/html/_static/interview_Melo.mp3
      - ls $READTHEDOCS_OUTPUT/html
      - ls $READTHEDOCS_OUTPUT/html/_static

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
