version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - cd docs/ && npm install
    - cd docs/ && npm run build
    - mkdir -p $READTHEDOCS_OUTPUT/html/_static
    - cp docs/resources/interview_Melo.mp3 $READTHEDOCS_OUTPUT/html/_static/interview_Melo.mp3
    - cp --recursive docs/build/* $READTHEDOCS_OUTPUT/html/

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
